### ISSUE TITLE
Shader won't load

### ISSUE THREAD

**Issue by DARKLOL680** [jbritain/Ebin-Shaders-Resurrected#1]
**Describe the bug**
i'm using Iris in 1.20.1 and i'm getting this error message in the chat when trying to load the shader
net.minecraft.class_2973: Invalid shaders/core/textured.json: The call method_34416 is not cancellable.

**Specifications (please complete the following information):**
 - OS: Windows 10
 - GPU: NVIDIA RTX 4070
 - CPU: i5-13600k

**Comment by ruvaldak** [comment]
me too

**Comment by jbritain** [comment]
I can't replicate this issue right now, but I'm on AMD. I will look into it though, and see if I can find a fix.

**Comment by jbritain** [comment]
What version of Iris are you using? This looks to me like it could be more of an issue with Iris than the shader. A `latest.log` would also be nice since error messages are broken in Iris 1.7.

**Comment by ruvaldak** [comment]
Iris 1.7, on AMD Linux mesa drivers.

X0nk's Bliss shader had an identical "34416 not cancelable" earlier that Null managed to fix. Perhaps ask Null how he fixed that. 

[Here's an entire log, as well, from your shader](https://mclo.gs/aXsQPvd)

[And here's a log where I go into a single player world and try to load every version from 1.0 to 1.8, in order. None of them compile properly.](https://mclo.gs/aXsQPvd)

**Comment by jbritain** [comment]
Hi, thanks for the log. Looks like the error messages are equally broken in the log files on Iris. If you're having the issue on AMD, that's surprising. I might have to load up on Linux and see if I can replicate it there.

For your logs on older versions, you seem to have attached the same link again, a 1.6 log would definitely be useful!

**Comment by ruvaldak** [comment]
My apologies, I sure did share the same link twice. This should be the right link: https://mclo.gs/BWg6uLH

**Comment by jbritain** [comment]
Alright, thanks. I've managed to get the issue replicating on Linux now.

**Comment by jbritain** [comment]
Oh, you meant all versions of the *shader*! Versions 1.0-1.3 or so did not work on AMD anyway, but that was fixed in newer versions.

**Comment by DARKLOL680** [comment]
now the shader load thanks
but the shadows do not, there's no shadows for me

**Comment by jbritain** [comment]
> now the shader load thanks but the shadows do not, there's no shadows for me

Okay, do you mind creating a new issue for this?
Also,
- Try it on Iris 1.6, and send me your logs, so I can debug further.
- Does this occur with PCSS shadows turned off?
