### ISSUE TITLE
World Border Doesn't Render

### ISSUE THREAD

**Issue by MrZeroSkill** [jbritain/Ebin-Shaders-Resurrected#4]
**Describe the bug**
World border is invisible with shaders active.

**To Reproduce**
1. Teleport to world border or decrease its size such that it is within render distance

**Expected behavior**

**Screenshots**
![2024-07-10_16 20 27](https://github.com/jbritain/Ebin-Shaders-Resurrected/assets/156875233/a7d196b2-043a-4182-a5e6-ee73a1975127)
![2024-07-10_16 20 29](https://github.com/jbritain/Ebin-Shaders-Resurrected/assets/156875233/f471b0a2-768e-417e-a6c5-65691c65abb3)

**Minecraft Version/Mods (please complete the following information):**
 - Minecraft 1.20.6
 - Iris 1.7.0
 - Other mods below
 ```
Explosive Enhancement
EMI
MidnightLib
Cherished Worlds
Better Mount HUD
Reese's Sodium Options
Entity Texture Features
EntityCulling
Mod Menu
Visuality
Entity Model Features
Resourcify
Debugify
ModernFix
Noxesium
Architectury
FastQuit
Fabric Language Kotlin
Fabric API
BadOptimizations
Language Reload
Cloth Config v14
MixinTrace
NotEnoughAnimations
Fast IP Ping
Status Effect Bars
CreativeCore
Indium
CraftPresence
Zoomify
Held Item Info
BetterF3
Iris
Continuity
Presence Footsteps
More Chat History
Polymorph
Emoji Type
Bobby
Client Tweaks
OptiGUI
Dark Loading Screen
e4mc
Chunky
Noisium
Lithium
Clumps
spark
FPS-Display
Sodium Extra
AmbientSounds
Euphoria Patcher
Dynamic FPS
Krypton
Balm
YetAnotherConfigLib
FerriteCore
KleeSlabs
Talk Bubbles
FabricSkyBoxes
Concurrent Chunk Management Engine
Yeetus Experimentus
Fadeless
Falling Leaves
Sound Physics Remastered
ImmediatelyFast
Shulker Box Tooltip
More Culling
Mouse Tweaks
3d-Skin-Layers
Better Statistics Screen
Enhanced Attack Indicator
Blur+ (Fabric)
Remove Reloading Screen
Better Ping Display
Sodium
```

**Specifications (please complete the following information):**
 - OS: Windows 11 23H2
 - GPU: NVIDIA GeForce RTX 4070 Super

**Additional context**
None

**PLEASE READ THE FOLLOWING BEFORE SUBMITTING AN ISSUE**
Ok

**Comment by jbritain** [comment]
Should be a relatively easy fix, will endeavor to resolve in the next release

**Comment by jbritain** [comment]
This is proving harder than expected to solve. For some reason the world border doesn't show up in the depth buffer.

**Comment by jbritain** [comment]
Transparency rendering is no longer dependent on the depth buffer 
![Yippee-meme-3](https://github.com/user-attachments/assets/1447b293-13c2-4b5d-95de-0ad801a416c5)
