### ISSUE TITLE
Rain outside causes wet effect inside

### ISSUE THREAD

**Issue by freakedenough** [jbritain/Ebin-Shaders-Resurrected#7]
This floor shouldnt look wet at all, as it is inside a building and rain is not hitting it.
1.21.1, Optifine, ESR 1.5.4
![2024-10-30_11 34 18](https://github.com/user-attachments/assets/bfa11e61-9011-4a72-93e1-20a6086426fe)

**Comment by jbritain** [comment]
I'll probably need to add a threshold to the lightmap data used for rain - will do
